services:
  web:
    image: ghcr.io/zjx-artcc/ids:master
    ports:
      - 3200:3000
    container_name: ids
    restart: unless-stopped
    environment:
      DEV_MODE: false
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      VATSIM_CLIENT_ID: ${VATSIM_CLIENT_ID}
      VATSIM_CLIENT_SECRET: ${VATSIM_CLIENT_SECRET}
      VATUSA_FACILITY: ${VATUSA_FACILITY}
      IS_STAFF_ENDPOINT: ${IS_STAFF_ENDPOINT}
      NEXT_PUBLIC_WEBSOCKET_URL: ${NEXT_PUBLIC_WEBSOCKET_URL}
      UPLOADTHING_TOKEN: ${UPLOADTHING_TOKEN}
